export const ENDPOINTS = {
  ATTACHMENT: {
    UPLOAD: '/file/:appId/attachments',
    DOWNLOAD: '/file/:appId/attachments/:id',
    DELETE: '/file/:appId/attachments/:id',
    GET_ALL: '/file/:appId/attachments',
    GET_BY_ID: '/file/:appId/attachments/:id',
    UPDATE: '/file/:appId/attachments/:id',
    UPDATE_PUT: '/file/:appId/attachments/:id',
  },
  ATTRIBUTES: {
    ADD: '/attributes/add',
    ADD_ALL: '/attributes/add/all',
    ADD_CHILD: '/attributes/add/child/:id',
    GET_ALL: '/attributes',
    GET_SHOWING: '/attributes/show',
    GET_SHOWING_TEST: '/attributes/show/test',
    UPDATE_MANY: '/attributes/update/many',
    GET_BY_ID: '/attributes/:id',
    GET_CHILD_BY_ID: '/attributes/child/:id/:ids',
    UPDATE: '/attributes/:id',
    UPDATE_MANY_CHILD: '/attributes/update/child/many',
    UPDATE_CHILD: '/attributes/update/child/:attributeId/:childId',
    UPDATE_STATUS: '/attributes/status/:id',
    UPDATE_CHILD_STATUS: '/attributes/status/child/:id',
    DELETE: '/attributes/:id',
    DELETE_CHILD: '/attributes/delete/child/:attributeId/:childId',
    DELETE_MANY: '/attributes/delete/many',
    DELETE_MANY_CHILD: '/attributes/delete/child/many',
  },
  AUTH: {
    REGISTER: '/user/auth/register',
    SOCIAL_REGISTER: '/user/auth/social-register',
    CONFIRM_ACCOUNT: '/user/auth/confirm-account/:token',
    LOGIN: '/user/auth/login',
    CUSTOM_LOGIN: '/user/auth/custom/login',
    CHECK_AUTH: '/user/auth/checkAuth',
    CHECK_USER: '/user/auth/checkUser',
    VERIFY_SESSION: '/user/auth/verify/session',
    REFRESH_TOKEN: '/user/auth/session/refresh/token',
    RESET_PASSWORD: '/user/auth/reset-password/:token',
    FORGOT_PASSWORD: '/user/auth/forget-password',
    CHANGE_PASSWORD: '/user/auth/change-password',
    PROFILE: '/user/auth/profile',
    UPDATE_PROFILE: '/user/auth/profile/update',
    LOGOUT: '/user/auth/logout',
  },
  USERS: {
    GET_ALL: '/users',
    GET_BY_ID: '/users/:id',
    GET_PROFILE: '/users/customer/profile',
    UPDATE_BY_ID_PATCH: '/users/:id',
    UPDATE_BY_ID_PUT: '/users/:id',
    DELETE_BY_ID: '/users/:id',
  },
  PRODUCTS: {
    GET_ALL: '/products',
    GET_BY_ID: '/products/:id',
    CREATE: '/products',
    CREATE_BULK: '/products/bulk',
    GET_SHOW: '/products/show',
    GET_RELATED: '/products/related',
    GET_DISCOUNT: '/products/discount',
    GET_POPULAR: '/products/popular',
    GET_BY_SLUG: '/products/view/:slug',
    GET_DETAILS: '/products/details',
    UPDATE_PATCH: '/products/:id',
    UPDATE_PUT: '/products/:id',
    DELETE: '/products/:id',
    SEARCH: '/products/search',
    GET_REVIEWS: '/products/:product_id/reviews',
    ADD_REVIEW: '/products/:product_id/reviews',
    BULK_UPLOAD: '/products/bulk-upload',
    FEATURED: '/products/featured',
  },
  CATEGORIES: {
    CREATE: '/categories',
    GET_ALL: '/categories',
    GET_BY_ID: '/categories/:id',
    UPDATE_PUT: '/categories/:id',
    UPDATE_PATCH: '/categories/:id',
    DELETE: '/categories/:id',
    PRODUCT_COUNT: '/categories/data/product-count',
    SHOW: '/categories/data/show',
  },
  CART: {
    ADD_ITEM: '/cart/add',
    ADD_ITEM_TO_CART: '/cart/:id/add',
    REMOVE_ITEM_FROM_CART: '/cart/:id/remove',
    CHECKOUT: '/cart/:id/checkout',
    GET_CARTS_BY_USER: '/cart/:user_id',
    GET_SINGLE_CART_BY_USER: '/cart/:user_id/:id',
    GET_SINGLE_CART: '/cart/:id',
    GET_ALL_CARTS: '/cart',
    UPDATE_CART_PUT: '/cart/:id',
    UPDATE_CART_PATCH: '/cart/:id',
    DELETE_CART: '/cart/:id',
  },
  ORDERS: {
    CREATE: '/orders/create',
    CANCEL: '/orders/cancel/:id',
    VERIFY_PAYMENT: '/orders/verify-payment',
    GET_ALL: '/orders',
    GET_BY_ID: '/orders/:id',
    UPDATE_PUT: '/orders/:id',
    UPDATE_PATCH: '/orders/:id',
    DELETE: '/orders/:id',
    DOWNLOAD_INVOICE: '/orders/:id/invoice',
    GET_BY_USER: '/orders/user/:userId',
    GET_CUSTOMER_ORDERS: '/orders/customer/fetch',
    GET_CUSTOMER_DASHBOARD: '/orders/customer/dashboard',
    GET_USER_ORDER_BY_ID: '/orders/user/:userId/:orderId',
    UPDATE_USER_ORDER_PATCH: '/orders/user/:userId/:orderId',
    UPDATE_USER_ORDER_PUT: '/orders/user/:userId/:orderId',
    DELETE_USER_ORDER: '/orders/user/:userId/:orderId'
   
  },
  PAYMENTS: {
    CREATE: '/payments',
    VERIFY: '/payments/verify',
    GET_BY_ORDER: '/payments/order/:orderId',
    REFUND: '/payments/:id/refund',
  },
  WISHLIST: {
    ADD_ITEM: '/wishlist/add',
    ADD_PRODUCT: '/wishlist/:id/add',
    REMOVE_PRODUCT: '/wishlist/:id/remove',
    GET_ITEMS: '/wishlist/fetch',
    GET_ALL: '/wishlists',
    GET_SINGLE: '/wishlist/:id',
    UPDATE_PUT: '/wishlist/:id',
    UPDATE_PATCH: '/wishlist/:id',
    DELETE: '/wishlist/:id',
  },
  ADDRESS: {
    GET_ALL: '/address',
    GET_BY_ID: '/address/:id',
    CREATE: '/address',
    UPDATE: '/address/:id',
    UPDATE_PUT: '/address/:id',
    DELETE: '/address/:id',
    SET_DEFAULT: '/address/:id/default',
  },
  COUPONS: {
    ADD: '/coupon/add',
    APPLY: '/coupon/apply',
    ADD_ALL: '/coupon/add/all',
    GET_ALL: '/coupon',
    GET_SHOWING: '/coupon/show',
    GET_BY_ID: '/coupon/:id',
    UPDATE_BY_ID: '/coupon/:id',
    UPDATE_MANY: '/coupon/update/many',
    UPDATE_STATUS: '/coupon/status/:id',
    DELETE_BY_ID: '/coupon/:id',
    DELETE_MANY: '/coupon/delete/many',
  },
  REVIEWS: {
    // For /products/:product_id/reviews and /reviews/:product_id
    ADD_REVIEW_TO_PRODUCT: '/products/:product_id/reviews',
    GET_REVIEWS_FOR_PRODUCT: '/products/:product_id/reviews',
    GET_SINGLE_REVIEW_FOR_PRODUCT: '/products/:product_id/reviews/:review_id',
    UPDATE_REVIEW_FOR_PRODUCT_PATCH: '/products/:product_id/reviews/:review_id',
    UPDATE_REVIEW_FOR_PRODUCT_PUT: '/products/:product_id/reviews/:review_id',
    DELETE_REVIEW_FOR_PRODUCT: '/products/:product_id/reviews/:review_id',

    ADD_REVIEW: '/reviews/:product_id',
    GET_REVIEWS: '/reviews/:product_id',
    GET_SINGLE_REVIEW: '/reviews/:product_id/:review_id',
    UPDATE_REVIEW_PATCH: '/reviews/:product_id/:review_id',
    UPDATE_REVIEW_PUT: '/reviews/:product_id/:review_id',
    DELETE_REVIEW: '/reviews/:product_id/:review_id',
  },
  NOTIFICATIONS: {
    GET_ALL: '/notifications',
    MARK_AS_READ: '/notifications/:id/read',
    DELETE: '/notifications/:id',
  },
  SETTINGS: {
    GET: '/settings',
    UPDATE: '/settings',
  },
  BRAND: {
    CREATE: '/brands',
    GET_ALL: '/brands',
    GET_BY_ID: '/brands/:id',
    UPDATE: '/brands/:id',
    UPDATE_PATCH: '/brands/:id',
    DELETE: '/brands/:id',
  },
  CONTACTS: {
    CREATE: '/contact',
    GET_ALL: '/contact',
    GET_BY_ID: '/contact/:id',
    UPDATE_PATCH: '/contact/:id',
    UPDATE_PUT: '/contact/:id',
    DELETE: '/contact/:id',
    BULK_DELETE: '/contact/bulk',
    REMOVE: '/contact/remove/:id',
    REMOVE_BULK: '/contact/remove/bulk',
  },
  // Add more endpoints here as needed for your application
};
export const PUBLIC_ENDPOINTS = {
  GET_CATEGORIES: '/categories',
  GET_PRODUCTS: '/products',
  GET_PRODUCT_BY_ID: '/products/:id',
  SEARCH_PRODUCTS: '/products/search',
};
